<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Procyon.Logging.Abstractions\Procyon.Logging.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <PackageId>Procyon.Logging</PackageId>
    <Version>0.1.0</Version>
    <Description>Lightweight config-driven JSON file logging for ASP.NET Core applications</Description>
    <PackageTags>logging;json;files;middleware;dotnet;procyon</PackageTags>
    <RepositoryUrl>https://github.com/rudrprasad05/nuget</RepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
